from typing import AsyncIterator, List, Optional

from backend.app.services.ai.gemini.service import GeminiService
from backend.app.services.ai.gemini.exceptions import GeminiError
from backend.app.services.ai.streaming.models import StreamChunk, StreamResult
from backend.app.services.ai.streaming.exceptions import (
    StreamingError,
    InvalidStreamError,
    StreamInterruptedError,
)

class StreamingService:
    """Service layer managing Gemini streaming responses, validations, and text reconstruction."""
    
    def __init__(self, gemini_service: GeminiService) -> None:
        """Initializes the service with constructor-injected GeminiService.
        
        Args:
            gemini_service: Gemini API service.
        """
        self.gemini_service = gemini_service

    def _validate_prompts(self, system_prompt: str, user_prompt: str) -> None:
        """Validates that prompts are not empty or whitespace."""
        if not system_prompt or not system_prompt.strip():
            raise InvalidStreamError("System prompt cannot be empty or whitespace.")
        if not user_prompt or not user_prompt.strip():
            raise InvalidStreamError("User prompt cannot be empty or whitespace.")

    async def stream_response(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> AsyncIterator[StreamChunk]:
        """Streams the response from Gemini incrementally, wrapping each chunk in a StreamChunk.
        
        Args:
            system_prompt: Guidelines/role for the model.
            user_prompt: User input to respond to.
            
        Yields:
            Incremental StreamChunk objects.
            
        Raises:
            InvalidStreamError: If prompts are empty or stream yields no content.
            StreamInterruptedError: If the API stream fails mid-stream.
            StreamingError: For other unexpected streaming errors.
        """
        self._validate_prompts(system_prompt, user_prompt)
        
        try:
            gemini_stream = self.gemini_service.generate_stream(
                system_prompt=system_prompt,
                user_prompt=user_prompt
            )
        except GeminiError as e:
            # Map startup connection errors
            raise StreamingError(f"Failed to initiate stream: {str(e)}", original_error=e) from e
        except Exception as e:
            raise StreamingError(f"Unexpected error starting stream: {str(e)}", original_error=e) from e

        sequence = 0
        prev_text: Optional[str] = None
        
        try:
            async for text in gemini_stream:
                if not text:
                    continue
                if prev_text is not None:
                    yield StreamChunk(content=prev_text, is_final=False, sequence=sequence)
                    sequence += 1
                prev_text = text
        except GeminiError as e:
            # Map mid-stream failures
            raise StreamInterruptedError(f"Stream was interrupted mid-generation: {str(e)}", original_error=e) from e
        except Exception as e:
            raise StreamInterruptedError(f"Unexpected stream interruption: {str(e)}", original_error=e) from e
            
        if prev_text is not None:
            yield StreamChunk(content=prev_text, is_final=True, sequence=sequence)
        else:
            raise InvalidStreamError("No content was generated by the stream.")

    async def collect_stream(self, system_prompt: str, user_prompt: str) -> StreamResult:
        """Collects all chunks from the stream and returns the reconstructed StreamResult.
        
        Args:
            system_prompt: Guidelines/role for the model.
            user_prompt: User input to respond to.
            
        Returns:
            The complete StreamResult.
        """
        chunks: List[StreamChunk] = []
        async for chunk in self.stream_response(system_prompt, user_prompt):
            chunks.append(chunk)
            
        full_text = self.reconstruct_response(chunks)
        return StreamResult(chunks=chunks, full_text=full_text)

    def reconstruct_response(self, chunks: List[StreamChunk]) -> str:
        """Reconstructs the full response text from a list of StreamChunks after verifying sequence order and integrity.
        
        Args:
            chunks: Chronological list of StreamChunks.
            
        Returns:
            Reconstructed full string response.
            
        Raises:
            InvalidStreamError: If sequence ordering is broken, chunks contain empty content, or final flags are invalid.
        """
        if not chunks:
            raise InvalidStreamError("No stream chunks provided for reconstruction.")
            
        for idx, chunk in enumerate(chunks):
            # Validate sequence number
            if chunk.sequence != idx:
                raise InvalidStreamError(f"Invalid sequence order: expected {idx}, got {chunk.sequence}.")
                
            # Validate non-empty chunk content
            if not chunk.content:
                raise InvalidStreamError(f"Chunk at sequence {chunk.sequence} has empty content.")
                
            # Validate final chunk flags
            is_last = (idx == len(chunks) - 1)
            if chunk.is_final != is_last:
                if chunk.is_final:
                    raise InvalidStreamError(f"Chunk at sequence {chunk.sequence} is marked final, but is not the last chunk.")
                else:
                    raise InvalidStreamError("The last chunk in the stream must be marked final.")
                    
        return "".join(chunk.content for chunk in chunks)
