"""align schemas and seed personas

Revision ID: 8f28c31ea5fd
Revises: 7e169c60cd24
Create Date: 2026-07-15 13:13:59.780328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8f28c31ea5fd'
down_revision: Union[str, None] = '7e169c60cd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('communication_score', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('learning_roadmap', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('persona_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('ended_at')
        batch_op.drop_column('started_at')

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_style', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('supported_difficulty_levels', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('focus_areas', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('system_context', sa.Text(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executive_summary', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('performance_overview', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('strengths', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('weaknesses', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('recommendations', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('learning_roadmap', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('markdown_report', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('overall_score')
        batch_op.drop_column('technical_score')
        batch_op.drop_column('feedback')
        batch_op.drop_column('communication_score')
        batch_op.drop_column('confidence_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('communication_score', sa.NUMERIC(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('technical_score', sa.NUMERIC(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('overall_score', sa.NUMERIC(precision=5, scale=2), nullable=False))
        batch_op.drop_column('generated_at')
        batch_op.drop_column('markdown_report')
        batch_op.drop_column('learning_roadmap')
        batch_op.drop_column('recommendations')
        batch_op.drop_column('weaknesses')
        batch_op.drop_column('strengths')
        batch_op.drop_column('performance_overview')
        batch_op.drop_column('executive_summary')

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('system_context')
        batch_op.drop_column('focus_areas')
        batch_op.drop_column('supported_difficulty_levels')
        batch_op.drop_column('interview_style')

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('ended_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('persona_id',
               existing_type=sa.String(length=50),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('topics')

    op.drop_table('evaluations')
    # ### end Alembic commands ###

