from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from backend.app.services.ai.personas.models import PersonaType

class StartInterviewRequest(BaseModel):
    """Request payload to initiate a new interview session."""
    persona_id: PersonaType = Field(description="Interviewer persona ID.")
    topics: Optional[List[str]] = Field(default_factory=lambda: ["Python"], description="Topics list.")
    difficulty: Optional[str] = Field("mid", description="Difficulty level.")

class StartInterviewResponse(BaseModel):
    """Response payload returned when an interview successfully starts."""
    interview_id: str = Field(description="Unique interview session ID.")
    question: str = Field(description="Opening question from the interviewer.")
    question_number: int = Field(description="Sequential question index starting at 1.")

class SendMessageRequest(BaseModel):
    """Request payload containing the candidate response."""
    message: str = Field(min_length=1, description="The message text from the candidate.")

class SendMessageResponse(BaseModel):
    """Response payload containing the follow-up question."""
    question: str = Field(description="The follow-up question generated by the AI.")
    question_number: int = Field(description="The sequential index of this follow-up question.")

class CompleteInterviewResponse(BaseModel):
    """Response payload indicating success of interview completion."""
    status: str = Field("completed", description="The final status of the interview.")

class InterviewListItemSchema(BaseModel):
    """Schema representing an interview item in a list."""
    id: str = Field(description="Unique interview session ID.")
    status: str = Field(description="Current status of the interview.")
    persona: str = Field(description="Persona ID string.")
    created_at: datetime = Field(description="Creation timestamp.")
    completed_at: Optional[datetime] = Field(None, description="Completion timestamp.")

class InterviewMetadataSchema(BaseModel):
    """Schema representing detailed interview configuration metadata."""
    topics: List[str] = Field(description="List of topics.")
    difficulty: str = Field(description="Difficulty level.")
    persona_id: str = Field(description="Persona ID.")
    created_at: datetime = Field(description="Created timestamp.")
    completed_at: Optional[datetime] = Field(None, description="Completed timestamp.")

class ConversationSummaryTurnSchema(BaseModel):
    """Schema representing a single message turn for listing detailed interview histories."""
    role: str = Field(description="Role of the speaker (interviewer/candidate).")
    content: str = Field(description="Content of the message.")
    timestamp: datetime = Field(description="Timestamp of the message.")

class InterviewDetailResponse(BaseModel):
    """Response payload returned for individual interview retrieval requests."""
    metadata: InterviewMetadataSchema = Field(description="Interview metadata.")
    conversation_summary: List[ConversationSummaryTurnSchema] = Field(description="Chronological message turns.")
    status: str = Field(description="Current status of the interview.")
